Write a python program to add below matrices
X = [[12,7,3], [4 ,5,6], [7 ,8,9]] Y = [[5,8,1],

[6,7,3], [4,5,9]]

''' 
    @Author: Dhananjay Kumar
    @Date: 18-11-2024 
    @Last Modified by: Dhananjay Kumar 
    @Last Modified time: 18-11-2024 
    @Title : Linear Algebra Question 1.
'''

In [6]:
import numpy as np

In [7]:
X =np.array( [[12, 7, 3],[4, 5, 6],[7, 8, 9]])
Y = np.array([ [5, 8, 1],[6, 7, 3],[4, 5, 9]])

result = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]

for i in range(len(X)): 
    for j in range(len(X[0])): 
        result[i][j] = X[i][j] + Y[i][j]

print("Resultant Matrix:")
for row in result:
    print(row)

Resultant Matrix:
[np.int64(17), np.int64(15), np.int64(4)]
[np.int64(10), np.int64(12), np.int64(9)]
[np.int64(11), np.int64(13), np.int64(18)]


''' 
    @Author: Dhananjay Kumar 
    @Date: 18-11-2024 
    @Last Modified by: Dhananjay Kumar 
    @Last Modified time: 18-11-2024
    @Title : Linear Algebra Question 2 
''' 2. Write a program to perform scalar multiplication of matrix and a number'''


In [9]:
X = [[12,7,3], [4 ,5,6], [7 ,8,9]] 
Y = 9
import numpy as np
Y = 9
x = np.array([[12,7,3],[4 ,5,6],[7 ,8,9]])
a = np.ones((3,3))
a = Y*x
print(a)

[[108  63  27]
 [ 36  45  54]
 [ 63  72  81]]


'''
    @Author: Dhananjay Kumar 
    @Date: 18-11-2024 
    @Last Modified by: Dhananjay Kumar 
    @Last Modified time: 18-11-2024 
    @Title : Linear Algebra Question 3 
''''
 '''
3. Write a program to perform multiplication of given matrix and vector X = [[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]], Y = [1, 2, 3]

'''

In [10]:
X = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
Y = np.array([1, 2, 3])

z=np.zeros((3,1))
for i in range(len(X)): 
    for j in range(len(Y)): 
        z[i] += X[i][j] * Y[j]

print(z)

[[16.]
 [ 6.]
 [ 8.]]


''' 
    @Author: Dhananjay Kumar
    @Date: 18-11-2024
    @Last Modified by: Dhananjay Kumar
    @Last Modified time: 18-11-2024
    @Title : Linear Algebra Question 4""" 
    4. Write a program to multiply matrices in problem 1
'''


In [14]:
X =np.array( [[12, 7, 3],[4, 5, 6],[7, 8, 9]])
Y = np.array([ [5, 8, 1],[6, 7, 3],[4, 5, 9]])

In [15]:
z = np.zeros((3,3))
for i in range(len(X)):
    for j in range(len(Y[0])):
        for k in range(len(Y)):
            z[i][j] += X[i][k]*Y[k][j]
print(z)



[[114. 160.  60.]
 [ 74.  97.  73.]
 [119. 157. 112.]]



"""
  @Author: Dhananjay Kumar
  @Date: 18-11-2024
  @Last Modified by: Dhananjay Kumar 
  @Last Modified time: 18-11-2024 
  @Title : Linear Algebra Question 5
""" 
  5. Write a program to find inverse matrix of matrix X in problem 1

In [16]:
X
a = np.linalg.inv(X)
print("Inverse of X: \n", a)


Inverse of X: 
 [[  1.          13.          -9.        ]
 [ -2.         -29.          20.        ]
 [  1.          15.66666667 -10.66666667]]


''' 
    @Author: Dhananjay Kumar 
    @Date: 18-11-2024 
    @Last Modified by: Dhananjay Kumar 
    @Last Modified time: 18-11-2024 
    @Title : Linear Algebra Question 6
'''
""" 6. Write a program to find transpose matrix of matrix Y in problem 1"""

In [ ]:
def transpose(X):
    y=np.zeros((X.shape[1],X.shape[0]))
    for i in range(X.shape[0]):
        for j in range(X.shape[1]):
            y[j][i]=X[i][j]
    return y
print("Transpose of a matrix X is : \n",transpose(X))